// AutoGenerated file by Arduino (Reef Angel build) 

/*
 * Copyright 2012 Reef Angel
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef __REEFANGEL_FEATURES_H__
#define __REEFANGEL_FEATURES_H__

#define CUSTOM_MENU_ENTRIES 9
#define InstalledRelayExpansionModules 2
#define OVERRIDE_PORTS
#define ATO_HIGH_REVERSE
#define MOONPHASELABEL
#define WATERLEVELEXPANSION
#define CUSTOM_MENU
#define RelayExp
#define SaveRelaysPresent
#define DateTimeSetup
#define NUMBERS_8x16
#define FONT_8x8
#define CUSTOM_VARIABLES
#define CUSTOM_MAIN
#define wifi
#define RFEXPANSION
#define DisplayLEDPWM
#define VersionMenu
#define WDT


#endif  // __REEFANGEL_FEATURES_H__
