// AutoGenerated file by Arduino (Reef Angel build) 

/*
 * Copyright 2012 Reef Angel
 *
 * Licensed under the Apache License, Version 2.0 (the "License")
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#ifndef __REEFANGEL_FEATURES_H__
#define __REEFANGEL_FEATURES_H__

#define StandardLightSetup
#define OverheatSetup
#define ATOSetup
#define WavemakerSetup
#define InstalledRelayExpansionModules 3
#define MetalHalideSetup
#define I2C_SC16IS750_2 0x4C
#define I2C_SC16IS750_1 0x48
#define DISPLAY_TANK
#define SC16IS750
#define MULTIWATERLEVELEXPANSION
#define RA_STAR
#define RelayExp
#define wifi
#define VersionMenu
#define WDT


#endif  // __REEFANGEL_FEATURES_H__
